TRAN-68: Redux and redux-saga, auth and re-auth mechanisms
SD-TransIT/transit_frontend pull request #11
Opened 2022-08-25 09:44 UTC by sniedzielski

TICKET: https://sd-transit.atlassian.net/browse/TRAN-68

NOTE: login form will be improved as a part of https://sd-transit.atlassian.net/browse/TRAN-66. For the purpose of showing login working I decided to push simple skeleton (but requires to wrap into Form component, add some validations)

Description of changes:
- installed redux, redux-saga and jwt-decode
- implement fetching 'token' and 'refresh token' with using 'saga'.
- added 'ProtectedRoute' component
- added mechanism for checking if token is valid. 
- added mechanism for 'refresh token'
- add simple form (this will be improved in TRAN-66)
- removed <React.StrictMode>
- updated test for 'LoginPage'

2022-08-25 10:04 UTC, KarolinaKopacz commented on src/pages/signIn/SignInPage.tsx
> +function SignInPage(props: any) {
Maybe instead of  `(props: any)` and` const { refresh, signIn } = props;`
write `function SignInPage({ refresh, signIn })`

2022-08-25 10:04 UTC, KarolinaKopacz commented on src/pages/signIn/SignInPage.tsx
> +    const data: any = {
Try to avoid type `any` ;)

2022-08-25 10:04 UTC, KarolinaKopacz commented on src/pages/signIn/SignInPage.tsx
> +    const data: any = {
Try to avoid type `any` ;)

2022-08-25 10:04 UTC, KarolinaKopacz commented on src/pages/signIn/SignInPage.tsx
> +const mapDispatchToProps = (dispatch: any) => ({
Try to avoid type `any` if it's possible ;)

2022-08-25 11:20 UTC, sniedzielski commented on src/pages/signIn/SignInPage.tsx
> +function SignInPage(props: any) {
I will try with this approach.

2022-08-25 11:20 UTC, sniedzielski commented on src/pages/signIn/SignInPage.tsx
> +    const data: any = {
ok

2022-08-25 20:06 UTC, awalkowiak requested changes

2022-08-25 20:06 UTC, awalkowiak commented on src/utils/authHelper.tsx
> +export default function isAuthenticatedProperly(): boolean {
I'd call it `isAuthenticated`

2022-08-25 20:06 UTC, awalkowiak commented on src/utils/authHelper.tsx
> +  const isAuthenticated = !!localStorage.getItem('token');
I think that if token is expired then you are not authenticated. I'd suggest change this to: 
```
export default function isAuthenticated(): boolean {
  const token = localStorage.getItem('token');
  if (token) {
    const tokenJson = JSON.parse(token);
    // Check if token is valid
  }

  return false;
}
```

2022-08-25 20:06 UTC, awalkowiak commented on src/routes/RoutesConfig.tsx
> +        element={<ProtectedRoute {...defaultProtectedRouteProps} outlet={<LandingPage />} />}
Do you have to pass this here? Why not just define it in the `ProtectedRoute`? Is there a case you'd want to redirect somewhere else other than the `sign in` page if someone is not authenticated? You could avoid this spreading here.

2022-08-25 20:07 UTC, awalkowiak commented
@sniedzielski few minor change requests, plus some conflicts occured

2022-08-26 08:24 UTC, sniedzielski commented
@awalkowiak I've just pushed my fixes after review. FYI I will apply Karolina's clues in next PR regarding LoginForm (https://sd-transit.atlassian.net/browse/TRAN-66).

2022-08-26 08:45 UTC, awalkowiak approved these changes

2022-08-26 08:45 UTC, merged