TRAN-87: Added searcher and table to the Customer master page
SD-TransIT/transit_frontend pull request #47
Opened 2022-09-14 13:25 UTC by KarolinaKopacz

**Add a table with Customer data and filtering**

**Implemented solution detail:**

![TRAN-87](https://user-images.githubusercontent.com/80507519/190166174-28702687-4789-4517-89cc-3f4689bce02b.gif)

2022-09-14 15:01 UTC, sniedzielski requested changes
@KarolinaKopacz Please fix one line. Also I wonder if we should rename CustomerMaster into 'Customer'.

2022-09-14 15:01 UTC, sniedzielski commented on src/pages/menuUpload/customerMaster/CustomerMasterPage.tsx
> +  // const dispatch = useDispatch();
can you remove this?

2022-09-15 07:30 UTC, KarolinaKopacz commented on src/pages/menuUpload/customerMaster/CustomerMasterPage.tsx
> +  // const dispatch = useDispatch();
Of course!

2022-09-15 07:31 UTC, KarolinaKopacz commented on src/pages/menuUpload/customerMaster/CustomerMasterPage.tsx
> +  // const dispatch = useDispatch();
@sniedzielski ready!

2022-09-15 08:09 UTC, sniedzielski approved these changes

2022-09-15 08:10 UTC, merged